version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pyinstaller  # Ensure pyinstaller is installed

  build:
    commands:
      - echo Building the executable...
      - pyinstaller --onefile ui.py

  post_build:
    commands:
      - echo Build complete
      - echo Listing the contents of the dist directory...
      - dir dist
      - echo Zipping the executable...
      - powershell Compress-Archive -Path dist\ui.exe -DestinationPath dist\tictactoe-executable.zip
      - echo Copying the zipped executable to the S3 bucket...
      - aws s3 cp dist\tictactoe-executable.zip s3://nomad-tictactoe-project/tictactoe-executable.zip
